@startuml sabolearn
' テーマ
!theme toy

' 設定
title "Sabo Learn"
skinparam titleBorderRoundCorner 10
skinparam titleBorderThickness 0
skinparam titleFontSize 22
skinparam titleFontColor #3F3D56


' エンティティ

entity users {
+ id [PK]
--
  name
  email
  password_digest
  birthday
  coin
  provider
  uid
# solo_wallpaper_id [FK]
# multi_wallpaper_id [FK]
  is_new_user
  created_at
  updated_at
}

entity musics {
+ id [PK]
--
  title
  artist
  src
  price
  is_default
  created_at
  updated_at
}

entity wallpapers {
+ id [PK]
--
  title
  src
  price
  is_default_solo
  is_default_multi
  created_at
  updated_at
}

entity music_purchases {
+ id [PK]
--
# music_id[FK]
# user_id[FK]
  created_at
  updated_at
}

entity wallpaper_purchases {
+ id [PK]
--
# wallpaper_id[FK]
# user_id[FK]
  created_at
  updated_at
}

entity playlists {
+ id [PK]
--
# user_id[FK]
  name
  music_order
  created_at
  updated_at
}

entity playlists_musics {
+ id [PK]
--
# playlist_id[FK]
# music_id[FK]
  created_at
  updated_at
}

' リレーション
users ||-r-{ music_purchases
music_purchases }-r-|| musics
users ||-l-{ wallpaper_purchases
wallpaper_purchases }-d-|| wallpapers
users ||-r-|| playlists
playlists ||-r-{ playlists_musics
playlists_musics }-d-|| musics
