version: "3.8"

services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 3307:3307

  api:
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle _2.4.20_ install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
      - ./backend/vendor/bundle:/api/vendor/bundle
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  front:
    build: ./frontend/
    volumes:
      - ./frontend/app:/front
    ports:
      - 4000:3000
    command: sh -c "npm install && npm run dev"
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql-data: